echo "copy 1"
cp stage1_fast_rcnn_solver30k40k.pt conv_stage1_fast_rcnn_solver30k40k.pt
cp stage1_fast_rcnn_train.pt	    conv_stage1_fast_rcnn_train.pt
cp stage1_rpn_solver60k80k.pt	    conv_stage1_rpn_solver60k80k.pt
cp stage1_rpn_train.pt		    conv_stage1_rpn_train.pt
cp stage2_fast_rcnn_solver30k40k.pt conv_stage2_fast_rcnn_solver30k40k.pt
cp stage2_fast_rcnn_train.pt	    conv_stage2_fast_rcnn_train.pt
cp stage2_rpn_solver60k80k.pt	    conv_stage2_rpn_solver60k80k.pt
cp stage2_rpn_train.pt		    conv_stage2_rpn_train.pt
echo "copy 2"
cp stage1_fast_rcnn_solver30k40k.pt fc_stage1_fast_rcnn_solver30k40k.pt
cp stage1_fast_rcnn_train.pt	    fc_stage1_fast_rcnn_train.pt
cp stage1_rpn_solver60k80k.pt	    fc_stage1_rpn_solver60k80k.pt
cp stage1_rpn_train.pt		    fc_stage1_rpn_train.pt
cp stage2_fast_rcnn_solver30k40k.pt fc_stage2_fast_rcnn_solver30k40k.pt
cp stage2_fast_rcnn_train.pt	    fc_stage2_fast_rcnn_train.pt
cp stage2_rpn_solver60k80k.pt	    fc_stage2_rpn_solver60k80k.pt
cp stage2_rpn_train.pt		    fc_stage2_rpn_train.pt
echo "copy 3"
cp stage1_fast_rcnn_solver30k40k.pt prun_conv_stage1_fast_rcnn_solver30k40k.pt
cp stage1_fast_rcnn_train.pt	    prun_conv_stage1_fast_rcnn_train.pt
cp stage1_rpn_solver60k80k.pt	    prun_conv_stage1_rpn_solver60k80k.pt
cp stage1_rpn_train.pt		    prun_conv_stage1_rpn_train.pt
echo "copy 4"
cp stage2_fast_rcnn_solver30k40k.pt prun_fc_stage2_fast_rcnn_solver30k40k.pt
cp stage2_fast_rcnn_train.pt	    prun_fc_stage2_fast_rcnn_train.pt
cp stage2_rpn_solver60k80k.pt	    prun_fc_stage2_rpn_solver60k80k.pt
cp stage2_rpn_train.pt		    prun_fc_stage2_rpn_train.pt